# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TemperaturaServidor.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19TemperaturaServidor.proto\x12\x13temperatura_servico\"\x1d\n\x0bStatusReply\x12\x0e\n\x06status\x18\x01 \x01(\t\"E\n\x0bTemperatura\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\x12\x13\n\x0blocalizacao\x18\x02 \x01(\t\x12\x13\n\x0btemperatura\x18\x03 \x01(\x01\"N\n\x10TemperaturasList\x12:\n\x10temperatura_dado\x18\x01 \x03(\x0b\x32 .temperatura_servico.Temperatura2\xc8\x02\n\x13TemperaturaServidor\x12\\\n\x14\x43\x61\x64\x61strarTemperatura\x12 .temperatura_servico.Temperatura\x1a .temperatura_servico.StatusReply\"\x00\x12\x65\n\x18\x42uscarTemperaturaPorData\x12%.temperatura_servico.TemperaturasList\x1a .temperatura_servico.StatusReply\"\x00\x12l\n\x1f\x42uscarTemperaturaPorLocalizacao\x12%.temperatura_servico.TemperaturasList\x1a .temperatura_servico.StatusReply\"\x00\x42\x37\n\x1bio.grpc.examples.iotserviceB\x0fIoTServiceProtoP\x01\xa2\x02\x04TEMPb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'TemperaturaServidor_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\033io.grpc.examples.iotserviceB\017IoTServiceProtoP\001\242\002\004TEMP'
  _STATUSREPLY._serialized_start=50
  _STATUSREPLY._serialized_end=79
  _TEMPERATURA._serialized_start=81
  _TEMPERATURA._serialized_end=150
  _TEMPERATURASLIST._serialized_start=152
  _TEMPERATURASLIST._serialized_end=230
  _TEMPERATURASERVIDOR._serialized_start=233
  _TEMPERATURASERVIDOR._serialized_end=561
# @@protoc_insertion_point(module_scope)
