# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import TemperaturaServidor_pb2 as TemperaturaServidor__pb2


class TemperaturaServidorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CadastrarTemperatura = channel.unary_unary(
                '/temperatura_servico.TemperaturaServidor/CadastrarTemperatura',
                request_serializer=TemperaturaServidor__pb2.Temperatura.SerializeToString,
                response_deserializer=TemperaturaServidor__pb2.StatusReply.FromString,
                )
        self.BuscarTemperaturaPorData = channel.unary_unary(
                '/temperatura_servico.TemperaturaServidor/BuscarTemperaturaPorData',
                request_serializer=TemperaturaServidor__pb2.TemperaturasList.SerializeToString,
                response_deserializer=TemperaturaServidor__pb2.StatusReply.FromString,
                )
        self.BuscarTemperaturaPorLocalizacao = channel.unary_unary(
                '/temperatura_servico.TemperaturaServidor/BuscarTemperaturaPorLocalizacao',
                request_serializer=TemperaturaServidor__pb2.TemperaturasList.SerializeToString,
                response_deserializer=TemperaturaServidor__pb2.StatusReply.FromString,
                )


class TemperaturaServidorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CadastrarTemperatura(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BuscarTemperaturaPorData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BuscarTemperaturaPorLocalizacao(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TemperaturaServidorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CadastrarTemperatura': grpc.unary_unary_rpc_method_handler(
                    servicer.CadastrarTemperatura,
                    request_deserializer=TemperaturaServidor__pb2.Temperatura.FromString,
                    response_serializer=TemperaturaServidor__pb2.StatusReply.SerializeToString,
            ),
            'BuscarTemperaturaPorData': grpc.unary_unary_rpc_method_handler(
                    servicer.BuscarTemperaturaPorData,
                    request_deserializer=TemperaturaServidor__pb2.TemperaturasList.FromString,
                    response_serializer=TemperaturaServidor__pb2.StatusReply.SerializeToString,
            ),
            'BuscarTemperaturaPorLocalizacao': grpc.unary_unary_rpc_method_handler(
                    servicer.BuscarTemperaturaPorLocalizacao,
                    request_deserializer=TemperaturaServidor__pb2.TemperaturasList.FromString,
                    response_serializer=TemperaturaServidor__pb2.StatusReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'temperatura_servico.TemperaturaServidor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TemperaturaServidor(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CadastrarTemperatura(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/temperatura_servico.TemperaturaServidor/CadastrarTemperatura',
            TemperaturaServidor__pb2.Temperatura.SerializeToString,
            TemperaturaServidor__pb2.StatusReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BuscarTemperaturaPorData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/temperatura_servico.TemperaturaServidor/BuscarTemperaturaPorData',
            TemperaturaServidor__pb2.TemperaturasList.SerializeToString,
            TemperaturaServidor__pb2.StatusReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BuscarTemperaturaPorLocalizacao(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/temperatura_servico.TemperaturaServidor/BuscarTemperaturaPorLocalizacao',
            TemperaturaServidor__pb2.TemperaturasList.SerializeToString,
            TemperaturaServidor__pb2.StatusReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
